source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'rails_12factor', group: :production
gem 'pg'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'tzinfo-data'
gem "font-awesome-rails"

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'haml'

gem 'pg_search'

gem 'paperclip'
gem "paperclip-storage-ftp"

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
  gem 'capybara'
  gem 'factory_girl'

  # launchy automatically opens pages with capybara (great for debugging)
  gem 'launchy'

  gem 'database_cleaner'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :developlent do
  gem 'annotate'
end


