# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  database: leo-prototype-dev
  host: localhost
  port: 5432
  pool: 5
  username: leo-prototype
  password: leo-prototype

development:
  <<: *default
  database: leo-prototype-dev

test:
  <<: *default
  database: leo-prototype-test

production:
  <<: *default
  database: leo-prototype-prod

