frontend:
  build: frontend
  ports:
    - "80:80"
  volumes:
    - "./frontend:/app"

users:
  build: users
  environment:
    RACK_ENV: "development"
  volumes:
    - "./users:/usr/src/app"
  ports:
    - "4567:4567"
  links:
   - database

database:
  image: postgres:8.4
