source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.5'
gem 'sinatra-contrib', '~> 1.4.2'
gem 'sinatra-advanced-routes', :require => 'sinatra/advanced_routes'

gem 'thin', '~> 1.6.3'

gem 'activerecord', '~> 4.1.6'
gem 'sinatra-activerecord', '~> 2.0.2'
gem 'sqlite3'

gem 'rerun'

gem 'rspec', '~> 3.1.0'
gem 'byebug'
