source 'https://rubygems.org'

ruby '2.0.0'

gem 'rake', '10.0.3'
gem 'rails', '4.0.2'
gem 'pg', '0.17.0'

gem 'curb', '0.8.4'
gem 'mediawiki-gateway', '~> 0.5.1'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'less-rails' # Needed for less-version of flatui

group :development, :test do
  gem 'annotate', '2.5.0'
  gem 'rspec-rails', '2.14.0'
  gem 'guard-rspec', '2.4.0'
  gem 'guard-spork', '1.5.1'
  gem 'spork', '~> 1.0rc'
  gem 'spork-rails', '4.0.0'
  gem 'libnotify', '0.8.0'
  gem 'rb-inotify', '~> 0.9'
  gem 'cucumber-rails', '1.4.0', :require => false
  gem 'cucumber', '1.3.10'
  gem "database_cleaner", '1.0.0.RC1'
  gem 'guard-cucumber'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '4.0.1'
  gem 'coffee-rails', '4.0.1'
  gem 'uglifier', '1.2.3'
  gem 'therubyracer', '~> 0.11.4'
end

gem 'jasmine'

# User authentication
gem 'devise', '~> 3.2'
gem 'figaro'

group :test do
  gem 'capybara', '1.1.2'
  gem 'factory_girl_rails', '4.2.1'
  gem "email_spec", ">= 1.4.0"
  gem 'simplecov', '>=0.4.2', :require => false
  gem 'ci_reporter', '1.8.0'
end

group :deploy do
  gem 'capistrano', '~> 2.15.5'
  gem 'capistrano-chef', :git => 'https://github.com/JanAhrens/capistrano-chef.git'
end

gem 'thin', '~> 1.5.0'
gem 'faye', '~> 0.8.8'

# TODO: we should move to strong parameters and then remove this Gem dependency
gem 'protected_attributes'
gem 'haml', '~> 4.0.5'
gem 'twitter-bootstrap-rails', git: 'https://github.com/seyhunak/twitter-bootstrap-rails.git', branch: 'bootstrap3'
