# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box     = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  config.vm.customize ['modifyvm', :id, '--memory', 1024]

  config.vm.forward_port  3000,  3000 # thin
  config.vm.forward_port    80,  4000 # nginx
  config.vm.forward_port 15672, 15672 # rabbitmq_management plugin

  config.vm.provision :chef_client do |chef|
    chef.chef_server_url         = 'https://api.opscode.com/organizations/vedascan'
    chef.validation_client_name  = 'vedascan-validator'
    chef.validation_key_path     = '.chef/validation.pem'

    chef.add_recipe 'vedascan'
  end
end
