source 'https://rubygems.org'
ruby "2.1.1"

gem 'rails', '4.1.1'
gem 'pg'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
# gem 'therubyracer',  platforms: :ruby

gem 'devise', '~> 3.0.4'
gem 'haml'
gem 'slim'
gem 'acts_as_list'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem "active_model_serializers"

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :development, :test do
  gem 'rspec-rails', '2.14.2'
  gem 'spring-commands-rspec'
  gem 'guard-rspec'
  gem 'spring'
  gem 'annotate'
  gem 'simplecov', '~> 0.7.1'
  gem 'factory_girl'
end

group :production do
  gem 'rails_12factor'
end
