#!/bin/bash

. "$(dirname "$0")/../../config"

id=$1

if [[ -z "${id}" ]]; then
  echo "${0} id"
  exit
fi

if [[ "${id}" != "23" && "${MOCK_MODE}" = "1" ]]; then
  exit
fi

curl ${CURL_OPTS} "${HOST}/decisions/${id}/facts" | ${POST_PROCESSING}
