#!/bin/bash

. `dirname $0`/../../config

id=$1

if [[ -z "${id}" ]]; then
  echo "$0 id"
  exit 1
fi

if [[ "${MOCK_MODE}" = "1" && "${id}" != "23" ]]; then
  exit
fi

curl ${CURL_OPTS} "${HOST}/decisions/${id}/participants" | ${POST_PROCESSING}
