development:
  adapter: postgresql
  database: dmc_development
  host: localhost
  port: 5432
  pool: 5
  username: dmc2
  password: dmc

test:
  adapter: postgresql
  database: dmc_test
  host: localhost
  port: 5432
  pool: 5
  username: dmc2
  password: dmc

production:
  adapter: postgresql
  database: dmc-prototype_production
  host: localhost
  port: 5432
  pool: 5
  username: dmc-prototype
  password: 

