#!/bin/bash

. "$(dirname "$0")/../../../config"

decision_id=$1
rating_id=$2

if [[ -z "${decision_id}" ]]; then
  echo "${0} decision_id rating_id"
  exit
fi

if [[ "${MOCK_MODE}" = "1" ]]; then
  if [[ "${decision_id}" != "23" || "${rating_id}" != "572-52" ]]; then
    exit
  fi
fi

curl ${CURL_OPTS} "${HOST}/decisions/${decision_id}/facts/ratings/${rating_id}" | ${POST_PROCESSING}
