#!/bin/bash

. "$(dirname "${0}")/../../config"

decision_id=$1
assignment_id=$2

if [[ -z "${decision_id}" || -z "${assignment_id}" ]]; then
  echo "${0} decision_id assignment_id"
  exit 1
fi

curl ${CURL_OPTS} "${HOST}/decisions/${decison_id}/assignments/${assignment_id}" | ${POST_PROCESSING}
