source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'bootstrap-sass', '2.0.4'

group :development do
  gem 'annotate', '2.5.0'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier',     '>= 1.0.3'
end

gem 'jasmine'
gem 'rspec'

gem 'jquery-rails'

group :production do
  gem 'pg', '0.12.2'
end

gem 'thin'
gem 'faye'
gem 'wurzelzwerg', :path => 'vendor/gems/wurzelzwerg'
